#ifndef RESOURCE_MANAGER_INTERFACE_H_
#define RESOURCE_MANAGER_INTERFACE_H_

enum ResourcesNames_e {
  RESOURCE_INPUT_SIDE,
  RESOURCE_OUTPUT_SIDE,
  RESOURCE_CORRIDOR
};

#endif // RESOURCE_MANAGER_INTERFACE_H_
